version: "3.3"

services:
  db:
    image: postgres:latest
    container_name: mn_prototype_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mn_prototype
    volumes:
      - .:/code
    command: ./docker_commands.sh
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  pg_data:
