# Generated by Django 4.1 on 2022-08-23 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновление')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('group', models.ManyToManyField(blank=True, related_name='group', to=settings.AUTH_USER_MODEL, verbose_name='группа')),
            ],
            options={
                'verbose_name': 'доски',
                'verbose_name_plural': 'доски',
            },
        ),
        migrations.CreateModel(
            name='BoardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='данные')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновление')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.board', verbose_name='доска')),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'данные доски',
                'verbose_name_plural': 'данные доски',
            },
        ),
    ]
